randomize();
score = 0;
health = 50;
healthCounter = 0;
alarm[0] = obstacleInterval;
alarm[1] = beatInterval;
currentBeat = 1;
layer_set_visible("Blackout", false);
audio_play_sound(snd_ambience, 0, true);
audio_play_sound(snd_drum1, 1, true);
audio_play_sound(snd_applause, 1, false);